---
title: "Shelly Lachish's CV"
author: Shelly Lachish
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions_MyFormat.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1oHyUQ4dA_e5G2WHl8p2nszinrBz6gKxsR5Xve_P09Gs",  
  pdf_mode = params$pdf_mode
)

```


```{r align_dots}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```

Aside
================================================================================

```{r build_network}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
#datadrivencv::build_network_logo(CV$entries_data)
```


Contact {#contact .specialcontact}
--------------------------------------------------------------------------------

```{r contact_info}
CV %>% print_contact_info()
```


```{r view_download}
if(params$pdf_mode){
  cat("View this CV online [here](https://github.com/shellylac/CV_datadrivencv/)")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/shellylac/CV_datadrivencv/blob/master/ShellyL_CV.pdf)")
}
```


Tech Stack {#techstack}
--------------------------------------------------------------------------------

```{r skills_bar_techstack}
CV %>% print_skill_bars(data = CV$tech_stack)
```

Skills {#dataskills}
--------------------------------------------------------------------------------

```{r skills_bar_dataskills}
CV %>% print_skill_bars(data = CV$data_skills)
```


<!-- Research Papers {#researchskills} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r skills_bar_researchpapers} -->
<!-- CV %>% print_skill_bars(data = CV$research_papers) -->
<!-- ``` -->

Research Papers
--------------------------------------------------------------------------------
Please see my [Google Scholar](https://scholar.google.co.uk/citations?user=mt4I9G0AAAAJ&hl=en) page for a full list of my research papers.


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made in R with [**pagedown**](https://github.com/rstudio/pagedown).
Source code available [here](https://github.com/shellylac/CV_datadrivencv).
<!-- Last updated on `r Sys.Date()`. -->


Main
================================================================================

Dr Shelly Lachish {#title}
--------------------------------------------------------------------------------

```{r intro_text}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r education}
CV %<>% print_section('education')
```


Career Summary {data-icon=laptop}
--------------------------------------------------------------------------------

```{r career_summary}
CV %<>% print_section('career_summary')
```


<!-- Scientific Publications {data-icon=book} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r academic_articles} -->
<!-- CV %<>% print_section('academic_articles') -->
<!-- ``` -->


<!-- These breaks just force a new page so section doesnt get cut off -->
<!-- #<br> -->
<!-- #<br> -->
<!-- #<br> -->

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r teaching}
CV %<>% print_section('teaching_positions')
```


Grants and Awards  {data-icon=medal}
--------------------------------------------------------------------------------

```{r grants}
CV %<>% print_section('grants_and_awards')
```


Invited Seminars  {data-icon=comments}
--------------------------------------------------------------------------------

```{r seminars}
CV %<>% print_section('invited_seminars')
```


Professional Service  {data-icon=group}
--------------------------------------------------------------------------------

```{r prof_service}
CV %<>% print_section('professional_service')
```


Volunteering  {data-icon=hands-helping}
--------------------------------------------------------------------------------

```{r volunteering}
CV %<>% print_section('volunteering')
```


```{r print_links}
CV %<>% print_links()
```

Media  {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r press}
CV %<>% print_section('about_me_press')
```
